name: Seprate Jobs for Push and Pull

on:
    push:
        branches:
            - master
            - feature
    pull_request:
        branches:
            - master        

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Run form push event
              run: echo "Push detected ${{github.ref_name}}"
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Run form pull event
              run: echo "Pull detected ${{github.head_ref}}"